apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: ankitjhunjhunwala03/consumer:latest
        env:
          - name: DB_NAME
            value: product_db
          - name: DB_USER
            value: product_user
          - name: DB_PASSWORD
            value: product_pass
          - name: DB_HOST
            value: db-product
          - name: DB_PORT
            value: "5432"
          - name: KAFKA_URL
            value: kafka
          - name: KAFKA_PORT
            value: "9092"
          - name: AUTH_SERVICE_URL
            value: "http://localhost:8000"