apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ankitjhunjhunwala03/product-service:latest
        ports:
        - containerPort: 8000
        env:
          - name: DB_NAME
            value: product_db
          - name: DB_USER
            value: product_user
          - name: DB_PASSWORD
            value: product_pass
          - name: DB_HOST
            value: db-product
          - name: DB_PORT
            value: "5432"
          - name: KAFKA_URL
            value: kafka
          - name: KAFKA_PORT
            value: "9092"
          - name: AUTH_SERVICE_URL
            value: "http://localhost:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: LoadBalancer
